/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,g){if(a==Array.prototype||a==Object.prototype)return a;a[d]=g.value;return a},r=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var g=a[d];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");},t=r(this),u=function(a,d){if(d)a:{var g=t;a=a.split(".");for(var h=0;h<a.length-
1;h++){var e=a[h];if(!(e in g))break a;g=g[e]}a=a[a.length-1];h=g[a];d=d(h);d!=h&&null!=d&&p(g,a,{configurable:!0,writable:!0,value:d})}},v=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}},w=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):{next:v(a)}};
u("Promise",function(a){function d(){this.g=null}function g(b){return b instanceof e?b:new e(function(c){c(b)})}if(a)return a;d.prototype.h=function(b){if(null==this.g){this.g=[];var c=this;this.i(function(){c.l()})}this.g.push(b)};var h=t.setTimeout;d.prototype.i=function(b){h(b,0)};d.prototype.l=function(){for(;this.g&&this.g.length;){var b=this.g;this.g=[];for(var c=0;c<b.length;++c){var f=b[c];b[c]=null;try{f()}catch(k){this.j(k)}}}this.g=null};d.prototype.j=function(b){this.i(function(){throw b;
})};var e=function(b){this.h=0;this.i=void 0;this.g=[];this.s=!1;var c=this.j();try{b(c.resolve,c.reject)}catch(f){c.reject(f)}};e.prototype.j=function(){function b(k){return function(l){f||(f=!0,k.call(c,l))}}var c=this,f=!1;return{resolve:b(this.A),reject:b(this.l)}};e.prototype.A=function(b){if(b===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof e)this.C(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?
this.v(b):this.o(b)}};e.prototype.v=function(b){var c=void 0;try{c=b.then}catch(f){this.l(f);return}"function"==typeof c?this.D(c,b):this.o(b)};e.prototype.l=function(b){this.u(2,b)};e.prototype.o=function(b){this.u(1,b)};e.prototype.u=function(b,c){if(0!=this.h)throw Error("Cannot settle("+b+", "+c+"): Promise already settled in state"+this.h);this.h=b;this.i=c;2===this.h&&this.B();this.F()};e.prototype.B=function(){var b=this;h(function(){if(b.G()){var c=t.console;"undefined"!==typeof c&&c.error(b.i)}},
1)};e.prototype.G=function(){if(this.s)return!1;var b=t.CustomEvent,c=t.Event,f=t.dispatchEvent;if("undefined"===typeof f)return!0;"function"===typeof b?b=new b("unhandledrejection",{cancelable:!0}):"function"===typeof c?b=new c("unhandledrejection",{cancelable:!0}):(b=t.document.createEvent("CustomEvent"),b.initCustomEvent("unhandledrejection",!1,!0,b));b.promise=this;b.reason=this.i;return f(b)};e.prototype.F=function(){if(null!=this.g){for(var b=0;b<this.g.length;++b)m.h(this.g[b]);this.g=null}};
var m=new d;e.prototype.C=function(b){var c=this.j();b.m(c.resolve,c.reject)};e.prototype.D=function(b,c){var f=this.j();try{b.call(c,f.resolve,f.reject)}catch(k){f.reject(k)}};e.prototype.then=function(b,c){function f(n,q){return"function"==typeof n?function(y){try{k(n(y))}catch(z){l(z)}}:q}var k,l,A=new e(function(n,q){k=n;l=q});this.m(f(b,k),f(c,l));return A};e.prototype.catch=function(b){return this.then(void 0,b)};e.prototype.m=function(b,c){function f(){switch(k.h){case 1:b(k.i);break;case 2:c(k.i);
break;default:throw Error("Unexpected state: "+k.h);}}var k=this;null==this.g?m.h(f):this.g.push(f);this.s=!0};e.resolve=g;e.reject=function(b){return new e(function(c,f){f(b)})};e.race=function(b){return new e(function(c,f){for(var k=w(b),l=k.next();!l.done;l=k.next())g(l.value).m(c,f)})};e.all=function(b){var c=w(b),f=c.next();return f.done?g([]):new e(function(k,l){function A(y){return function(z){n[y]=z;q--;0==q&&k(n)}}var n=[],q=0;do n.push(void 0),q++,g(f.value).m(A(n.length-1),l),f=c.next();
while(!f.done)})};return e});var x=this||self,B=/^[\w+/_-]+[=]{0,2}$/,C=null,D=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&B.test(a)?a:""},E=function(a,d){function g(){}g.prototype=d.prototype;a.I=d.prototype;a.prototype=new g;a.prototype.constructor=a;a.H=function(h,e,m){for(var b=Array(arguments.length-2),c=2;c<arguments.length;c++)b[c-2]=arguments[c];return d.prototype[e].apply(h,b)}},F=function(a){return a};function G(a){if(Error.captureStackTrace)Error.captureStackTrace(this,G);else{var d=Error().stack;d&&(this.stack=d)}a&&(this.message=String(a))}E(G,Error);G.prototype.name="CustomError";var H=function(a,d){a=a.split("%s");for(var g="",h=a.length-1,e=0;e<h;e++)g+=a[e]+(e<d.length?d[e]:"%s");G.call(this,g+a[h])};E(H,G);H.prototype.name="AssertionError";var I=function(a,d){throw new H("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var J;var M=function(a,d){this.g=a===K&&d||"";this.h=L};M.prototype.toString=function(){return"Const{"+this.g+"}"};var L={},K={};var O=function(a,d){this.g=d===N?a:""};O.prototype.toString=function(){return this.g+""};var N={};var P=function(a){var d=new M(K,"https://apis.google.com/js/client.js");d instanceof M&&d.constructor===M&&d.h===L?d=d.g:(I("expected object of type Const, got '"+d+"'"),d="type_error:Const");if(void 0===J){var g=null;var h=x.trustedTypes;if(h&&h.createPolicy){try{g=h.createPolicy("goog#html",{createHTML:F,createScript:F,createScriptURL:F})}catch(f){x.console&&x.console.error(f.message)}J=g}else J=g}d=(g=J)?g.createScriptURL(d):d;d=new O(d,N);a:{try{var e=a&&a.ownerDocument,m=e&&(e.defaultView||e.parentWindow);
m=m||x;if(m.Element&&m.Location){var b=m;break a}}catch(f){}b=null}if(b&&"undefined"!=typeof b.HTMLScriptElement&&(!a||!(a instanceof b.HTMLScriptElement)&&(a instanceof b.Location||a instanceof b.Element))){b=typeof a;if("object"==b&&null!=a||"function"==b)try{var c=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(f){c="<object could not be stringified>"}else c=void 0===a?"undefined":null===a?"null":typeof a;I("Argument is not a %s (or a non-Element, non-Location mock); got: %s",
"HTMLScriptElement",c)}d instanceof O&&d.constructor===O?c=d.g:(c=typeof d,I("expected object of type TrustedResourceUrl, got '"+d+"' of type "+("object"!=c?c:d?Array.isArray(d)?"array":c:"null")),c="type_error:TrustedResourceUrl");a.src=c;(c=a.ownerDocument&&a.ownerDocument.defaultView)&&c!=x?c=D(c.document):(null===C&&(C=D(x.document)),c=C);c&&a.setAttribute("nonce",c)};var Q=function(){var a=document;var d="SCRIPT";"application/xhtml+xml"===a.contentType&&(d=d.toLowerCase());return a.createElement(d)};function R(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");S()}var S,T=null,U=window;
function V(){if(T)return T;window.performance.mark("gapi_load_start");var a=U.colabExperiments&&U.colabExperiments.first_party_auth;return T=new Promise(function(d,g){S=d;U.gapi_onload=function(){a?S():gapi.load("auth:client",R)};var h=Q();P(h);h.async=!0;h.onerror=function(){g(Error("Error loading "+h.src))};d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(h,d)})}U.colab_gapi_loader={load:V};V().then(function(){},function(){});
